"""Repair PostgreSQL audit ID generation lost in the UUID table rebuild."""
from alembic import op
import sqlalchemy as sa

revision = "2026091801"
down_revision = "2026091701"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return  # SQLite INTEGER PRIMARY KEY already generates IDs.
    # Prevent writes between reading the maximum and installing the generator.
    op.execute("LOCK TABLE audit_logs IN ACCESS EXCLUSIVE MODE")
    column = next(c for c in sa.inspect(bind).get_columns("audit_logs") if c["name"] == "id")
    if column.get("identity") or column.get("default"):
        return  # Preserve databases which already have a working generator.
    next_id = max(1, int(bind.scalar(sa.text("SELECT COALESCE(MAX(id), 0) FROM audit_logs"))) + 1)
    op.execute("ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(f"ALTER TABLE audit_logs ALTER COLUMN id RESTART WITH {next_id}")


def downgrade():
    # Data repair is intentionally retained: removing it would break writes again.
    pass
