"""Restore PostgreSQL IDs lost when allocation tables were rebuilt for UUIDs."""

from alembic import op
import sqlalchemy as sa


revision = "2026091901"
down_revision = "2026091801"
branch_labels = None
depends_on = None


def _restore_identity(table_name: str) -> None:
    bind = op.get_bind()
    op.execute(f"LOCK TABLE {table_name} IN ACCESS EXCLUSIVE MODE")
    column = next(c for c in sa.inspect(bind).get_columns(table_name) if c["name"] == "id")
    if column.get("identity") or column.get("default"):
        return
    next_id = max(1, int(bind.scalar(sa.text(f"SELECT COALESCE(MAX(id), 0) FROM {table_name}"))) + 1)
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute(f"ALTER TABLE {table_name} ALTER COLUMN id RESTART WITH {next_id}")


def upgrade():
    if op.get_bind().dialect.name != "postgresql":
        return  # SQLite INTEGER PRIMARY KEY already generates IDs.
    _restore_identity("supplier_allocations")
    _restore_identity("purchase_results")


def downgrade():
    # Data repair is intentionally retained: removing it would break writes again.
    pass
